/**
 * Oneloop API
 * API Key Management
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ApiKeyScope } from '../models/ApiKeyScope';
import { HttpFile } from '../http/http';

export class ApiKey {
    'id': string;
    'name': string;
    'maskedKey': string;
    'prefix': string | null;
    'expiresAt': number | null;
    'totalUsageLeft': number | null;
    'limitUsage': boolean;
    'scopes': Array<ApiKeyScope>;
    'enabled': boolean;
    'customerId': string | null;
    'deleted': boolean;
    'createdAt': string;
    'updatedAt': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "maskedKey",
            "baseName": "maskedKey",
            "type": "string",
            "format": ""
        },
        {
            "name": "prefix",
            "baseName": "prefix",
            "type": "string",
            "format": ""
        },
        {
            "name": "expiresAt",
            "baseName": "expiresAt",
            "type": "number",
            "format": ""
        },
        {
            "name": "totalUsageLeft",
            "baseName": "totalUsageLeft",
            "type": "number",
            "format": ""
        },
        {
            "name": "limitUsage",
            "baseName": "limitUsage",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "scopes",
            "baseName": "scopes",
            "type": "Array<ApiKeyScope>",
            "format": ""
        },
        {
            "name": "enabled",
            "baseName": "enabled",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "customerId",
            "baseName": "customerId",
            "type": "string",
            "format": ""
        },
        {
            "name": "deleted",
            "baseName": "deleted",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "string",
            "format": ""
        },
        {
            "name": "updatedAt",
            "baseName": "updatedAt",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ApiKey.attributeTypeMap;
    }

    public constructor() {
    }
}

