/**
 * Oneloop API
 * API Key Management
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class CreateApiKeyRequestScopesInner {
    'representation': string;
    'create': boolean;
    'read': boolean;
    'update': boolean;
    'del': boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "representation",
            "baseName": "representation",
            "type": "string",
            "format": ""
        },
        {
            "name": "create",
            "baseName": "create",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "read",
            "baseName": "read",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "update",
            "baseName": "update",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "del",
            "baseName": "del",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CreateApiKeyRequestScopesInner.attributeTypeMap;
    }

    public constructor() {
    }
}

