/**
 * Oneloop API
 * API Key Management
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ApiKeyScope } from '../models/ApiKeyScope';
import { HttpFile } from '../http/http';

export class CreateApiKeyRequest {
    'name': string;
    'workspaceId': string;
    'prefix'?: string;
    'expiresAt'?: number;
    'totalUsageAllowed'?: number;
    'scopes': Array<ApiKeyScope>;
    'enabled': boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "workspaceId",
            "baseName": "workspaceId",
            "type": "string",
            "format": ""
        },
        {
            "name": "prefix",
            "baseName": "prefix",
            "type": "string",
            "format": ""
        },
        {
            "name": "expiresAt",
            "baseName": "expiresAt",
            "type": "number",
            "format": ""
        },
        {
            "name": "totalUsageAllowed",
            "baseName": "totalUsageAllowed",
            "type": "number",
            "format": ""
        },
        {
            "name": "scopes",
            "baseName": "scopes",
            "type": "Array<ApiKeyScope>",
            "format": ""
        },
        {
            "name": "enabled",
            "baseName": "enabled",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CreateApiKeyRequest.attributeTypeMap;
    }

    public constructor() {
    }
}

