/**
 * Oneloop API
 * API Key Management
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ApiKey } from '../models/ApiKey';
import { HttpFile } from '../http/http';

export class DeleteApiKeyResponse {
    'apiKey': ApiKey;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "apiKey",
            "baseName": "apiKey",
            "type": "ApiKey",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return DeleteApiKeyResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

