/**
 * Oneloop API
 * API Key Management
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ApiKeyScope } from '../models/ApiKeyScope';
import { HttpFile } from '../http/http';

export class EditApiKeyRequest {
    'name'?: string;
    'enabled'?: boolean;
    'scopes'?: Array<ApiKeyScope>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "enabled",
            "baseName": "enabled",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "scopes",
            "baseName": "scopes",
            "type": "Array<ApiKeyScope>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return EditApiKeyRequest.attributeTypeMap;
    }

    public constructor() {
    }
}

