/**
 * Oneloop API
 * API Key Management
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { WorkspaceScope } from '../models/WorkspaceScope';
import { HttpFile } from '../http/http';

export class RetrieveAllWorkspaceScopesResponse {
    'scopes': Array<WorkspaceScope>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "scopes",
            "baseName": "scopes",
            "type": "Array<WorkspaceScope>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return RetrieveAllWorkspaceScopesResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

