/**
 * Oneloop API
 * API Key Management
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ApiKey } from '../models/ApiKey';
import { HttpFile } from '../http/http';

export class RetrieveApiKeysResponse {
    'apiKeys': Array<ApiKey>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "apiKeys",
            "baseName": "apiKeys",
            "type": "Array<ApiKey>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return RetrieveApiKeysResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

