/**
 * Oneloop API
 * API Key Management
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Workspace } from '../models/Workspace';
import { HttpFile } from '../http/http';

export class RetrieveWorkspaceResponse {
    'workspaces': Array<Workspace>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "workspaces",
            "baseName": "workspaces",
            "type": "Array<Workspace>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return RetrieveWorkspaceResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

