/**
 * Oneloop API
 * API Key Management
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CreateApiKeyResponseApiKey } from '../models/CreateApiKeyResponseApiKey';
import { HttpFile } from '../http/http';

export class RotateApiKeyResponse {
    'apiKey': CreateApiKeyResponseApiKey;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "apiKey",
            "baseName": "apiKey",
            "type": "CreateApiKeyResponseApiKey",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return RotateApiKeyResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

