/**
 * Oneloop API
 * API Key Management
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class VerifyApiKeyResponseRateLimit {
    'remaining': number;
    'resetAt': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "remaining",
            "baseName": "remaining",
            "type": "number",
            "format": ""
        },
        {
            "name": "resetAt",
            "baseName": "resetAt",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return VerifyApiKeyResponseRateLimit.attributeTypeMap;
    }

    public constructor() {
    }
}

