/**
 * Oneloop API
 * API Key Management
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class Workspace {
    'id': string;
    'name': string;
    'teamId': string;
    'defaultKeyPrefix': string | null;
    'defaultAllowedIPs': Array<string>;
    'defaultExpiration': number | null;
    'createdAt': string;
    'updatedAt': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "teamId",
            "baseName": "teamId",
            "type": "string",
            "format": ""
        },
        {
            "name": "defaultKeyPrefix",
            "baseName": "defaultKeyPrefix",
            "type": "string",
            "format": ""
        },
        {
            "name": "defaultAllowedIPs",
            "baseName": "defaultAllowedIPs",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "defaultExpiration",
            "baseName": "defaultExpiration",
            "type": "number",
            "format": ""
        },
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "string",
            "format": ""
        },
        {
            "name": "updatedAt",
            "baseName": "updatedAt",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Workspace.attributeTypeMap;
    }

    public constructor() {
    }
}

